= Laravel Tutorial
:toc: left
:toclevels: 5

* https://laravel-news.com/your-first-laravel-application[Laravel Tutorial: Step by Step Guide to Building Your First Laravel Application]

== laradock(docker) を使ったスタートアップガイド

* https://laravel-news.com/your-first-laravel-application[laradock - your-first-laravel-application]

[source,bash]
----
sudo apt update -y
sudo apt install -y php composer

composer create-project --prefer-dist laravel/laravel links "7.*"

git init
git add .
# 初期化したプロジェクトのソースを一式コミット
git commit

git submodule add https://github.com/Laradock/laradock.git
cd laradock
cp env-example .env
# COMPOSE_PROJECT_NAME を変えて docker のコンテナ名がコンフリクトしないようにする
vi .env

cd ../
# DATABASE の接続情報を laradock に合わせる
vi .env

docker-compose up -d nginx mysql phpmyadmin

docker-compose exec workspace bash
composer install
php artisan key:generate
----

== プロジェクト作成

[source,bash]
----
# Via the installer
laravel new links // <1>

# Via composer
composer create-project --prefer-dist laravel/laravel links "7.*"
----
<1> composer で laravel/installer をインストール済みの場合


== データベース初期化

`.env.example` をコピペして `.env` を作り、 DB の接続情報を設定する。
なお `.env` の中身は本番/検証環境などで異なるため git の管理対象外とするべき。

laradock を使って default と異なるデータベースを作る場合は、 `laradock/mysql/docker-entrypoint-initdb.d/createdb.sql.example` の内容にしたがって `createdb.sql` を作る。

[source,sql]
.sample
----
CREATE DATABASE IF NOT EXISTS `laraveltutorial` COLLATE 'utf8_general_ci' ;
GRANT ALL ON `laraveltutorial`.* TO 'default'@'%' ;

FLUSH PRIVILEGES ;
----

NOTE: 初回の `docker-compose up` 前に初期化用ファイルを作成すること。

初回のデータベースへの接続確認は migrate コマンドを使うと良い。

[source,bash]
----
php artisan migrate // <1>
----
<1> `artisan` は laravel 用のコマンドハンドラ(?)コマンドハブ(?)的なもの

== ユーザー登録/認証の仕組みを自動構築(Scaffolding)

* https://readouble.com/laravel/7.x/ja/authentication.html[Laravel 7.x 認証]
* https://laravel.com/docs/7.x/frontend[JavaScript & CSS Scaffolding]

次のコマンドを実行することで、ユーザーの登録やログインの仕組みを自動的に構築することができる。

[source,bash]
----
composer install laravel/ui
php artisan ui bootstrap --auth // <1>
----
<1> bootstrap 以外にも vue, react も選択できる

== migrate

migrate 用のファイルを生成する。

[source,bash]
----
php artisan make:migration create_links_table --create=links // <1>
----
<1> `database/migrations/{{datetime}}_create_links_table.php` を生成する。

[source,php]
.`database/migrations/{{datetime}}_create_links_table.php` 実装例
----
public function up()
{
    Schema::create('links', function (Blueprint $table) {
        $table->increments('id');
        $table->string('title');
        $table->string('url')->unique();
        $table->text('description');
        $table->timestamps();
    });
}
----

migrate を実行する。

[source,bash]
----
php artisan migrate
----

.migrate の方法
--
[horizontal]
`php artisan migrate`:: 通常の migrate 実行
`php artisan migrate:fresh`:: テーブルをすべてドロップしてから migrate
`php artisan migrate:fresh --seed`:: テーブルをすべてドロップしてから migrate してテストデータを投入
--

== model

model 用のファイルを生成する。

[source,bash]
----
php artisan make:model --factory Link // <1> <2>
----
<1> `app/Link.php` を生成する。
<2> `--factory` フラグをつけると、テストデータ用の `database/factories/LinkFactory.php` を生成する。

=== アプリ用

モデル(`app/Link.php`)のフィールドを固定するには `$fillable` プロパティを用いる。

[source,php]
----
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Link extends Model
{
    protected $fillable = [ // <1>
        'title',
        'url',
        'description'
    ];
}
----
<1> `$fillable` を用いて配列で定義したフィールドのみがコンストラクタで一括割当される。

=== テスト用

[source,php]
.`database/factories/LinkFactory.php` 実装例
----
<?php

/** @var \Illuminate\Database\Eloquent\Factory $factory */

use App\Link;
use Faker\Generator as Faker;

$factory->define(Link::class, function (Faker $faker) {
    return [
        'title' => substr($faker->sentence(2), 0, -1),
        'url' => $faker->url,
        'description' => $faker->paragraph,
    ];
});
----

テストデータを生成する seeder ファイルを生成する。

[source,bash]
----
php artisan make:seeder LinksTableSeeder // <1>
----
<1> `database/seeds/LinksTableSeeder.php` を生成する。

[source,php]
.`database/seeds/LinksTableSeeder.php` 実装例
----
public function run()
{
    factory(App\Link::class, 5)->create();
}
----

seeder を呼ぶためには `database/seeds/DatabaseSeeder.php` で call する必要がある。

[source,php]
.`database/seeds/DatabaseSeeder.php` 実装例
----
public function run()
{
    $this->call(LinksTableSeeder::class);
}
----

== controller(Routing)

ルーティングは `routes/web.php` で管理。

[source,php]
.`routes/web.php` 実装例
----
Route::get('/', function () {
    $links = \App\Link::all(); // <1>

    return view('welcome', ['links' => $links]); // <2> <3>
    // return view('welcome')->with('links', $links); // <4>
    // return view('welcome')->withLinks($links); // <4>
});
----
<1> データベースからデータを取得
<2> 第１引数の welcome でテンプレートファイルを指定。たぶん `resources/views/welcome.blade.php` を参照する
<3> 第２引数で変数をテンプレートファイルの定義へマッピング
<4> こんな書き方もできる(fluent API)

POST に対するバリデーションチェックも `routes/web.php` 内で処理(してもよい)。

[source,php]
.`routes/web.php` 内でのバリデーション実装例
----
use Illuminate\Http\Request;

Route::post('/submit', function (Request $request) {
    $data = $request->validate([ // <1>
        'title' => 'required|max:255',
        'url' => 'required|url|max:255',
        'description' => 'required|max:255',
    ]);

    $link = tap(new App\Link($data))->save(); // <2> <4>

    // $link = new \App\Link($data); // <3>
    // $link->save();

    // $link = new \App\Link; // <5>
    // $link->title = $data['title'];
    // $link->url = $data['url'];
    // $link->description = $data['description'];
    // $link->save();

    return redirect('/');
});
----
<1> バリデーション。不適な場合は例外がスローされ、エラー情報が view 側に渡される(?)
<2> `tap` ヘルパーを使うとモデルインスタンスが返るため `save()` が呼び出せる
<3> `tap` ヘルパーを使わない場合の例
<4> 引数の `$date` は、モデルで `$fillable` で定義したフィールドのみが設定される
<5> コンストラクタによる一括割当を避けたい場合の例

== view

view は `resources/views/xxx.blade.php` を編集する。
view の書き方をざっくり説明。

[source,php]
.`routes/web.php` 実装例
----
@extends('layouts.app') // <1>
@section('content') // <2>
    <div class="container">
        <div class="row">
            <h1>Submit a link</h1>
        </div>
        <div class="row">
            <form action="/submit" method="post">
                @csrf // <3>
                @if ($errors->any()) // <4>
                    <div class="alert alert-danger" role="alert">
                        Please fix the following errors
                    </div>
                @endif
                <div class="form-group">
                    <label for="title">Title</label>
                    <input type="text" class="form-control @error('title') is-invalid @enderror" id="title" name="title" placeholder="Title" value="{{ old('title') }}"> // <5>
                    @error('title') // <6>
                        <div class="invalid-feedback">{{ $message }}</div>
                    @enderror
                    // @if($errors->has('title')) // <7>
                    //     <div class="invalid-feedback">{{ $errors->first('title') }}</div>
                    // @endif
                </div>
                <div class="form-group">
                    <label for="url">Url</label>
                    <input type="text" class="form-control @error('url') is-invalid @enderror" id="url" name="url" placeholder="URL" value="{{ old('url') }}">
                    @error('url')
                        <div class="invalid-feedback">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="description">Description</label>
                    <textarea class="form-control @error('description') is-invalid @enderror" id="description" name="description" placeholder="description">{{ old('description') }}</textarea>
                    @error('description')
                        <div class="invalid-feedback">{{ $message }}</div>
                    @enderror
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
@endsection
----
<1> ベースとなるレイアウトをロードする(?)
<2> レイアウトのセクションにマッピングされる(?)
<3> CSRF 対策用のトークンを埋め込む(?)
<4> バリデーションエラーがある場合に表示
<5> `@error('title') is-invalid @enderror` エラーの場合は is-invalid が有効となる。またエラーの場合は `old('title')` により送信時の値を再設定する
<6> @error ディレクティブはエラーメッセージ変数 `$message` を提供する
<7> エラーハンドリングの別な書き方

== Test (UT, IT)

テスト用ファイルを生成する。

[source,bash]
----
php artisan make:test SubmitLinksTest
----

テストのサンプル。

[source,php]
----
<?php

namespace Tests\Feature;

use Illuminate\Validation\ValidationException;
use Tests\TestCase;
use Illuminate\Foundation\Testing\RefreshDatabase;

class SubmitLinksTest extends TestCase
{
    use RefreshDatabase; // <1>

    /** @test */
    function guest_can_submit_a_new_link()
    {
        $response = $this->post('/submit', [ // <2>
            'title' => 'Example Title',
            'url' => 'http://example.com',
            'description' => 'Example description.',
        ]);

        $this->assertDatabaseHas('links', [ // <3>
            'title' => 'Example Title'
        ]);

        $response // <4>
            ->assertStatus(302)
            ->assertHeader('Location', url('/'));

        $this // <5>
            ->get('/')
            ->assertSee('Example Title');
    }
}
----
<1> テストのたびにデータベースをリセットする旨の宣言
<2> テストデータの POST リクエスト
<3> データベースに登録されているか検証
<4> レスポンスのステータスコードとヘッダーの検証
<5> ホームページの html を取得し、期待値があることを検証

テストの実行。

[source,bash]
----
php artisan test

# Or run phpunit directly
vendor/bin/phpunit
----

=== テストのテクニック

[source,php]
----
/** @test */
function link_is_not_created_with_an_invalid_url()
{
    $this->withoutExceptionHandling(); // <1>

    $cases = ['//invalid-url.com', '/invalid-url', 'foo.com'];

    foreach ($cases as $case) {
        try {
            $response = $this->post('/submit', [
                'title' => 'Example Title',
                'url' => $case,
                'description' => 'Example description',
            ]);
        } catch (ValidationException $e) { // <2>
            $this->assertEquals(
                'The url format is invalid.',
                $e->validator->errors()->first('url')
            );
            continue;
        }

        $this->fail("The URL $case passed validation when it should have failed.");
    }
}
----
<1> 例外による HTTP レスポンス生成を抑止。これにより例外をそのまま検証できる
<2> 実際にサーバーサイドで発生している例外をキャッチして検証

== memo

dokcer 向けコマンド::
+
--
[source,bash]
----
# docker 起動
exec docker-compose up nginx mysql phpmyadmin

# テスト実行
exec docker-compose exec workspace php artisan test

# assets の監視起動
exec docker-compose exec workspace npm run watch
----
--

よく使う(かもしれない) artisan コマンド::
+
--
[source,bash]
----
# migrate 用ファイルを生成する
php artisan make:migration create_links_table --create=links

# migrate する
php artisan migrate

# (denger!!!) all drop してから migrate する
php artisan migrate:fresh

# (denger!!!) all drop してから migrate して seed を埋め込む(テストデータをインサートする)
php artisan migrate:fresh --seed

# モデルとファクトリーの生成
php artisan make:model --factory Link

# xxx テーブル用の seeder 生成(テストデータ生成用ファイルの生成)
php artisan make:seeder LinksTableSeeder

# feature test (機能テスト) 用のファイルを生成
php artisan make:test SubmitLinksTest

# test の実行
php artisan test
----
--

.チュートリアルにかかった時間
[cols="3a,1"]
|===
|Column heading 1 |Column heading 2

|laradock による環境構築
|2h

|テーブル周りの実装

* マイグレーションファイルの実装と実行
* テストデータ用のファクトリーの実装
* テストデータ用の seeder の実装
* テストデータの投入
|2h

|ルーティングとビュー

* ルーティングの実装
* ビューの実装
|1h

|フォームの実装

* ルーティングの実装
* ビューの実装
|1h

|サーバーサイドバリデーション

* バリデーションの実装
* モデルの実装
|1h

|フォームのテスト

* テストの実装
* テストの実行
|1h
|===

=== ディレクトリ構成

[source,bash]
----
$ tree --charset unicode -I "laradock|node_modules|vendor"
.
|-- README.adoc
|-- README.md
|-- app // <1>
|   |-- Console
|   |   `-- Kernel.php
|   |-- Exceptions
|   |   `-- Handler.php
|   |-- Http // <2>
|   |   |-- Controllers
|   |   |   |-- Auth
|   |   |   |   |-- ConfirmPasswordController.php
|   |   |   |   |-- ForgotPasswordController.php
|   |   |   |   |-- LoginController.php
|   |   |   |   |-- RegisterController.php
|   |   |   |   |-- ResetPasswordController.php
|   |   |   |   `-- VerificationController.php
|   |   |   |-- Controller.php
|   |   |   `-- HomeController.php
|   |   |-- Kernel.php
|   |   `-- Middleware
|   |       |-- Authenticate.php
|   |       |-- CheckForMaintenanceMode.php
|   |       |-- EncryptCookies.php
|   |       |-- RedirectIfAuthenticated.php
|   |       |-- TrimStrings.php
|   |       |-- TrustHosts.php
|   |       |-- TrustProxies.php
|   |       `-- VerifyCsrfToken.php
|   |-- Link.php
|   |-- Providers
|   |   |-- AppServiceProvider.php
|   |   |-- AuthServiceProvider.php
|   |   |-- BroadcastServiceProvider.php
|   |   |-- EventServiceProvider.php
|   |   `-- RouteServiceProvider.php
|   `-- User.php
|-- app.sh.example
|-- artisan
|-- bootstrap
|   |-- app.php
|   `-- cache
|       |-- packages.php
|       `-- services.php
|-- composer.json
|-- composer.lock
|-- config // <3>
|   |-- app.php
|   |-- auth.php
|   |-- broadcasting.php
|   |-- cache.php
|   |-- cors.php
|   |-- database.php
|   |-- filesystems.php
|   |-- hashing.php
|   |-- logging.php
|   |-- mail.php
|   |-- queue.php
|   |-- services.php
|   |-- session.php
|   `-- view.php
|-- database // <4>
|   |-- factories
|   |   |-- LinkFactory.php
|   |   `-- UserFactory.php
|   |-- migrations
|   |   |-- 2014_10_12_000000_create_users_table.php
|   |   |-- 2014_10_12_100000_create_password_resets_table.php
|   |   |-- 2019_08_19_000000_create_failed_jobs_table.php
|   |   `-- 2020_06_24_082747_create_links_table.php
|   `-- seeds
|       |-- DatabaseSeeder.php
|       `-- LinksTableSeeder.php
|-- package-lock.json
|-- package.json
|-- phpunit.xml
|-- public // <5>
|   |-- css
|   |   `-- app.css
|   |-- favicon.ico
|   |-- index.php
|   |-- js
|   |   `-- app.js
|   |-- mix-manifest.json
|   |-- robots.txt
|   `-- web.config
|-- resources // <6>
|   |-- js
|   |   |-- app.js
|   |   `-- bootstrap.js
|   |-- lang
|   |   `-- en
|   |       |-- auth.php
|   |       |-- pagination.php
|   |       |-- passwords.php
|   |       `-- validation.php
|   |-- sass
|   |   |-- _variables.scss
|   |   `-- app.scss
|   `-- views
|       |-- auth
|       |   |-- login.blade.php
|       |   |-- passwords
|       |   |   |-- confirm.blade.php
|       |   |   |-- email.blade.php
|       |   |   `-- reset.blade.php
|       |   |-- register.blade.php
|       |   `-- verify.blade.php
|       |-- home.blade.php
|       |-- layouts
|       |   `-- app.blade.php
|       |-- submit.blade.php
|       `-- welcome.blade.php
|-- routes // <7>
|   |-- api.php // <9>
|   |-- channels.php
|   |-- console.php
|   `-- web.php // <8>
|-- server.php
|-- storage // <10>
|   |-- app
|   |   `-- public
|   |-- framework
|   |   |-- cache
|   |   |   `-- data
|   |   |-- sessions
|   |   |   |-- 4odKW1J4rpdzPaPQzmN5q36hm00bLPZXthTGVnik
|   |   |   |-- SosLCHV00ngiRCOoEZA9ksOySpgGAVREEYbHAzEa
|   |   |   `-- xA8GDKciSsZCsmkhSWkhYbECT9Jviz7sAQFsIZXp
|   |   |-- testing
|   |   `-- views
|   |       |-- 6dc4b9091bb228f0c7a3eba910a93be3a76e84ca.php
|   |       |-- 781b7abdbe9aee2ceb9a178ff1cc449b56d3debb.php
|   |       |-- 7bdeb8b0c526bafc45b4cf9183b44ebc3b0f0478.php
|   |       |-- c6d615eb91fe3a0edd449165e94d034703bbb84d.php
|   |       `-- e7ac274255da24ad5c9a63a3e97c4afea0bdf25f.php
|   `-- logs
|       `-- laravel.log
|-- tests // <11>
|   |-- CreatesApplication.php
|   |-- Feature
|   |   `-- SubmitLinksTest.php
|   |-- TestCase.php
|   `-- Unit
`-- webpack.mix.js

41 directories, 103 files
----
<1> app はアプリのコアディレクトリ
<2> app/Http はコントローラ、ミドルウェア、フォームリクエストを設置する。アプリケーションへのリクエストを処理するロジックは、ほぼ全てこのディレクトリ内に設置する
<3> config は設定ファイルを格納する
<4> database はマイグレーション用ファイルやテストデータ用の factory / seeder を格納する
<5> public はすべてのリクエストのエントリーポイント
<6> resources はコンパイル前の assets や view(blade) を格納する
<7> routes はルーティングの定義ファイルを管理
<8> web.php は RouteServiceProvider の web ミドルウェアグループに属するルートで構成します。もしアプリケーションがステートフルならば、すべてのルートは web.php ファイルの中で定義されることになるでしょう。
<9> api.php は RouteServiceProvider の api ミドルウェアグループに属するルートで構成します。これらのルートを通るアプリケーションに対するリクエストは、セッションステートにアクセスする必要がないように、トークンを使って認証されることを意図しています。
<10> storage はコンパイルされたBladeテンプレート、ファイルベースのセッション、ファイルキャッシュなど、フレームワークにより生成されるファイルを保存する
<11> tests は自動テストを配置
